PackageIdentifier: Microsoft.DirectXSDK
PackageVersion: 9.29.1962.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe
  InstallerSha256: 705271dc83bfee54d9b94e028426e288d5f070784b7446d164f48ecfbb2a02cb
  ProductCode: "Microsoft DirectX SDK (June 2010)"
  InstallerSwitches:
    Silent: /U /F
    SilentWithProgress: /U /F
  InstallerLocale: en-US
ManifestType: installer
ManifestVersion: 1.0.0